<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.FirebirdSQL" Version="2.1.2.2" />
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RmModel\RmModel.csproj" />
  </ItemGroup>

</Project>
